# Canales de YouTube a monitorear
channels:
  # midudev
  - id: "UC8LeXCWOalN8SxlrPcG-PaQ"
    name: "midudev"
    enabled: true
    max_videos_per_check: 5
    min_duration_minutes: 5  # Solo procesar videos largos
    keywords_filter: ["tecnología", "programación", "IA", "desarrollo"]
    exclude_keywords: ["en vivo", "stream", "directo"]
  
  # nate gentile
  - id: "UC36xmz34q02JYaZYKrMwXng" 
    name: "Nate Gentile"
    enabled: true  # Deshabilitado por ahora
    max_videos_per_check: 3
    min_duration_minutes: 10
    keywords_filter: ["tecnología", "programación", "IA", "desarrollo"]
    exclude_keywords: ["patrocinado", "ad"]
  
  # dotcsv
  - id: "UCOTko-zmnQTcOxSRdg5_uOQ"
    name: "dotcsv"
    enabled: true
    max_videos_per_check: 4
    min_duration_minutes: 6
    keywords_filter: ["inteligencia artificial", "machine learning"]
    exclude_keywords: ["en vivo", "stream", "directo"]
  
  # dotcsv lab
  - id: "UC9a8b7c6d5e4f3g2h1i0j1k2"
    name: "dotcsv lab"
    enabled: true
    max_videos_per_check: 3
    min_duration_minutes: 8
    keywords_filter: ["inteligencia artificial", "machine learning"]
    exclude_keywords: ["en vivo", "stream", "directo"]

  # 
  

# Configuración global de descubrimiento
discovery:
  # Frecuencia de revisión (en horas)
  check_interval_hours: 6
  
  # Días hacia atrás para buscar nuevos videos
  lookback_days: 7
  
  # Filtros globales
  global_filters:
    min_views: 1000  # Mínimo de visualizaciones
    max_age_days: 30  # Máximo de antigüedad
    avoid_shorts: true  # Evitar contenido ya en formato Shorts
    
  # Límites de API
  api_limits:
    requests_per_day: 10000
    max_results_per_request: 50
